services:
  todo-app:
    container_name: client-todo-app
    build: .
    ports:
      - "3000:3000"
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - todo-app-data:/data/db
volumes:
  todo-app-data:
